### ISSUE TITLE
How to initialize using M031TD2AE external crystal oscillator

### ISSUE THREAD

**Issue by Alg-tech** [OpenNuvoton/M031BSP#12]
How to initialize using M031TD2AE external crystal oscillator ，I can not do it work    
Your demo are all internally crystalline
Can you provide me with one for HXT witch usart

**Comment by kchuang1** [comment]
Hi,

You can refer the Level1_GPIO_Ctl sample under SampleCode/Level1_Training folder.
Search the "HXT" keyword then you can find the code to initialize the external crystal.
