### ISSUE TITLE
Cannot Enable M032LD2AE UART1 clock

### ISSUE THREAD

**Issue by alihayek179** [OpenNuvoton/M031BSP#15]
I am trying to enable M032LD2AE UART1 clock, but the value of UART1CKEN (CLK_APBCLK0[17]) is not changing. I tried doing that using sample codes, and NuLink (debugger).

**Comment by kchuang1** [comment]
Hi,
Please refer the https://www.nuvoton.com/export/sites/nuvoton/files/product-related-information/Nuvoton-MCU-PSG.pdf 
M032LD2AE only have one UART (UART0), so it cannot enable UART1 clock.
